### ISSUE TITLE
Add Classroom and Doubt forum feature 

### ISSUE THREAD

**Issue by adarsh-technocrat** [codeforcauseorg/edu-client#336]
### Description
The proposal is focusing on adding Classroom and doubt forum feature in the application 

The proposal is part of the GSoC 2021 project.

#### TODO's

* [ ]  **Phase 1**

   * [x]  Week 1
       * [x]  Complete figma Design for mobile devices
       * [x]  Complete figma Design for iPads and Desktops
   * [x]  Week 2
       * [x]  Full code cleanup and remove any component that are not being used
       * [x]  Create Homepage design according to figma for all the screens
       * [x]   Create Mock server inside client to fetch the data from  Mock API
  * [ ]  Week 3
       * [x]  Try Ionic Components for the native look of mobile applications (Not certain)
       * [x]  Create some other tab components inside the applications removing anything that is not needed.
       * [x]   Create Mock server inside client to fetch the data from  Mock API
       * [ ] Make screens responsive for all designs.

> More Deliverables to be added

 cc: @Abhishek-kumar09  @vasudevsinghal

**Comment by adarsh-technocrat** [comment]
Hey, @Abhishek-kumar09  add this issue to the milestone I'll keep updating the issue with the weekly deliverables and what all we need to achieve in **phase 1**  and **phase 2**  in brief !!
